/*Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/

function evenFibonacciNumbers() {
	
	//get the input into an array
	var nums = [];
	for (var i=1; i <= 10; i++)  {
		nums.push(i);
	}
	
	//loop through input array and create a new array of fib sequence
	var fibSeqArray = [1,2]; //manually add one and two for now
	var nextFibTerm = undefined;
	var sumOfEvenValuedFibTerms = 0;
 	nums.forEach(function(item, index, array) {
	
		if (index > 1) {
			//new sequence is previous two added together
			nextFibTerm = fibSeqArray[index-1] + fibSeqArray[index-2];
			fibSeqArray.push(nextFibTerm);
		}
	});
	
 	fibSeqArray.forEach(function(item,index,array) {
		var isEvenNumber = (item % 2 === 0);
		if (isEvenNumber) {
			sumOfEvenValuedFibTerms += item;
			print("even terms: " + item);
		}
		
	});
 	
 	print("Sum of even terms: " + sumOfEvenValuedFibTerms);
}

evenFibonacciNumbers();